language: python
python:
  - "2.7"
sudo: true


install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      ci/travis-install-linux.sh;
    fi
  - tlmgr conf
  - make install CONTINUE=y
  - sudo -i texhash
script:
  - make -C test
after_script: ci/travis-after.sh
