# jekyll conf

# site conf
title: uit-thesis

permalink: pretty
relative_permalinks: true

url: http://egraff.github.io
baseurl: "/uit-thesis"

highlighter: pygments
pygments: true

markdown: redcarpet

# GitHub flavored Markdown
kramdown:
  input: GFM

exclude: ['.git']
paginate: 5

sass:
  sass_dir: _sass