# jekyll conf

baseurl: "/uit-thesis"

highlighter: pygments
pygments: true

markdown: redcarpet

# GitHub flavored Markdown
kramdown:
  input: GFM

permalink: /post/:title
exclude: ['Gemfile','Gemfile.lock','Rakefile','.git']
paginate: 4

sass:
  sass_dir: _sass