# jekyll conf

# site conf
title: uit-thesis

permalink: date

url: http://egraff.github.io
baseurl: /uit-thesis

# GitHub flavored Markdown
kramdown:
  input: GFM

exclude: ['.git']
paginate: 5

sass:
  sass_dir: _sass
